import * as fs from 'fs';
import * as path from 'path';

// --- 1. SCHEMAS ---
interface CameraView {
    viewID: string;
    label: string;
    cameraPosNode: string;
    cameraTargetNode: string;
    fov: number;
}

interface Interaction {
    actionID: string;
    label: string;
    memoryPoint: string;
    type: 'toggle' | 'button' | 'knob';
    radius: number;
    animation: string;
    states: number[];
    tooltip: string;
}

interface VehicleConfig {
    vehicleClass: string;
    author: string;
    version: string;
    cameraViews?: CameraView[];
    interactions: Interaction[];
}

// --- 2. PATH SETUP ---
// Assumes script is run from TasDyn-Interaction-Compat/compiler/
const inputDir = path.join(__dirname, '../configs');
const outputDir = path.join(__dirname, '../../addons/tasdyn_compat');

// Ensure directories exist
if (!fs.existsSync(inputDir)) {
    console.error(`[Tasman Dynamics Error] Config directory not found at: ${inputDir}`);
    process.exit(1);
}
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
}

// --- 3. THE COMPILER ENGINE ---
function compileConfigs() {
    console.log('========================================');
    console.log(' Tasman Dynamics - Compatibility Compiler');
    console.log('========================================\n');

    // Recursively find all JSON files (allows modders to organize by folders like /rhs/ or /vanilla/)
    const files = getAllJsonFiles(inputDir);
    
    if (files.length === 0) {
        console.log('No JSON configurations found. Exiting.');
        return;
    }

    // Initialize the output strings
    let sqfOutput = `// AUTOGENERATED BY TASMAN DYNAMICS COMPILER - DO NOT EDIT MANUALLY\n\n`;
    sqfOutput += `TasDyn_InteractionMap = createHashMap;\n\n`;

    let cppOutput = `// AUTOGENERATED BY TASMAN DYNAMICS COMPILER - DO NOT EDIT MANUALLY\n\n`;
    cppOutput += `class CfgVehicles {\n`;
    // We define a base class to ensure we don't break vanilla inheritance
    cppOutput += `    class AllVehicles;\n`; 

    let successCount = 0;

    for (const file of files) {
        try {
            const rawData = fs.readFileSync(file, 'utf-8');
            const vehicle: VehicleConfig = JSON.parse(rawData);

            // Basic Validation
            if (!vehicle.vehicleClass || !vehicle.interactions) {
                throw new Error('Missing required fields: vehicleClass or interactions array.');
            }

            console.log(`[+] Compiling: ${vehicle.vehicleClass} (by ${vehicle.author || 'Unknown'})`);

            // --- BUILD SQF HASHMAP ENTRY ---
            // Format: ["memoryPoint", "actionID", radius, "label", "type", "animation"]
            const interactionArray = vehicle.interactions.map(i => {
                return `["${i.memoryPoint}", "${i.actionID}", ${i.radius}, "${i.label}", "${i.type}", "${i.animation}"]`;
            }).join(',\n        ');
            
            sqfOutput += `// ${vehicle.vehicleClass}\n`;
            sqfOutput += `TasDyn_InteractionMap set ["${vehicle.vehicleClass}", [\n        ${interactionArray}\n]];\n\n`;

            // --- BUILD CPP INJECTION ---
            // We inject a custom init event handler directly into the vehicle class
            cppOutput += `    class ${vehicle.vehicleClass} {\n`;
            cppOutput += `        class EventHandlers {\n`;
            cppOutput += `            class TasDyn_Init {\n`;
            cppOutput += `                init = "(_this select 0) call TasDyn_fnc_initInteraction;";\n`;
            cppOutput += `            };\n`;
            cppOutput += `        };\n`;
            cppOutput += `    };\n\n`;

            successCount++;

        } catch (error) {
            console.error(`[-] FAILED to compile ${path.basename(file)}:`, error instanceof Error ? error.message : error);
        }
    }

    cppOutput += `};\n`;

    // --- 4. WRITE COMPILED FILES ---
    fs.writeFileSync(path.join(outputDir, 'autogen_interactions.sqf'), sqfOutput);
    fs.writeFileSync(path.join(outputDir, 'autogen_vehicles.cpp'), cppOutput);
    
    console.log('\n========================================');
    console.log(` Compilation Complete! Successfully compiled ${successCount}/${files.length} vehicles.`);
    console.log(` Output written to: addons/tasdyn_compat/`);
    console.log(' Ready for HEMTT build.');
    console.log('========================================\n');
}

// Helper function to recursively grab JSON files
function getAllJsonFiles(dirPath: string, arrayOfFiles: string[] = []): string[] {
    const files = fs.readdirSync(dirPath);

    files.forEach(function(file) {
        if (fs.statSync(dirPath + "/" + file).isDirectory()) {
            arrayOfFiles = getAllJsonFiles(dirPath + "/" + file, arrayOfFiles);
        } else if (file.endsWith('.json')) {
            arrayOfFiles.push(path.join(dirPath, "/", file));
        }
    });

    return arrayOfFiles;
}

// Run the compiler
compileConfigs();